version: '3.8'
services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - redis
    volumes:
      - ./server/configs/app.yaml:/etc/take-flight/app.yaml:ro
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
