version: '3.8'
services:
  auth:
    build: ./services/auth
    ports:
      - "8081:8080"

  users:
    build: ./services/users
    ports:
      - "8082:8080"

  flights:
    build: ./services/flights
    ports:
      - "8083:8080"
    environment:
      - AMADEUS_CLIENT_ID=${AMADEUS_CLIENT_ID}
      - AMADEUS_CLIENT_SECRET=${AMADEUS_CLIENT_SECRET}

  bookings:
    build: ./services/bookings
    ports:
      - "8084:8080"

  admin:
    build: ./services/admin
    ports:
      - "8085:8080"

  orchestrator:
    build: ./agents/orchestrator
    ports:
      - "8090:8080"

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  nats:
    image: nats:2
    ports:
      - "4222:4222"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_AUTH_URL=http://localhost:8081
      - VITE_API_USERS_URL=http://localhost:8082
      - VITE_API_FLIGHTS_URL=http://localhost:8083
      - VITE_API_BOOKINGS_URL=http://localhost:8084
      - VITE_API_ADMIN_URL=http://localhost:8085
      - VITE_API_ORCHESTRATOR_URL=http://localhost:8090
    depends_on:
      - auth
      - users
      - flights
      - bookings
      - admin
      - orchestrator
