version: '3.8'

services:
  # Backend server (Node.js)
  server:
    build: ./server
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=production
      - PORT=8081
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongodb
      - redis
    networks:
      - app-network

  # Frontend (Vite React)
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8081
      - VITE_SOCKET_URL=ws://localhost:8081
    depends_on:
      - server
    networks:
      - app-network

  # MongoDB database
  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  # Redis cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  mongodb_data:
  redis_data:

networks:
  app-network:
    driver: bridge
