apiVersion: apps/v1
kind: Deployment
metadata:
  name: takeflight-deployment
  
  spec:
  replicas: 3
selector:
  matchLabels:
    app: takeflight
  template:
    metadata:
      labels:
        app: takeflight
    spec:
      containers:
       - name: takeflight
    image: siyar/takeflight:latest
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: "1"
        memory: "500Mi"
      requests:
        cpu: "0.5"
        memory: "200Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: takeflight-service
spec:
  selector:
    app: takeflight
  ports:
    - protocol: TCP
      port: 80
  type: LoadBalancer
