service: take-flight

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    NODE_ENV: ${self:provider.stage}

package:
  artifact: lambda_deployment_package.zip

functions:
  app:
    handler: server/lambda.handler
    events:
      - http:
          path: /
          method: get
      - http:
          path: /{proxy+}
          method: any

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
