  service: take-flight

  provider:
    name: aws
    runtime: nodejs20.x
    stage: ${opt:stage, 'dev'}
    region: us-east-1
    environment:
      NODE_ENV: ${self:provider.stage}
    apiGateway:
      shouldStartNameWithService: true

  functions:
    app:
      handler: server/lambda.handler
      events:
        - http:
            path: /
            method: get
        - http:
            path: /{proxy+}
            method: any
    connectHandler:
      handler: server/connect.handler
      events:
        - websocket:
            route: $connect
    disconnectHandler:
      handler: server/disconnect.handler
      events:
        - websocket:
            route: $disconnect
    messageHandler:
      handler: server/message.handler
      events:
        - websocket:
            route: $default

  package:
    artifact: lambda_deployment_package.zip

  plugins:
    - serverless-offline

  custom:
    serverless-offline:
      httpPort: 3000
