service: take-flight

provider:
  name: aws 
  runtime: nodejs20.x
  stage: dev
  region: us-east-1 # Choose your preferred AWS region
  environment:
    NODE_ENV: production

functions:
  app:
    handler: server/lambda.handler
    events:
      - http:
          path: /
          method: get
      - http:
          path: /{proxy+}
          method: any

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
