server:
  host: 0.0.0.0
  port: 8080
mongodb:
  uri: mongodb://localhost:27017
  database: takeflight
redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
jwt:
  secret: example-secret
  expireHours: 24
  refreshSecret: example-refresh-secret
  refreshTTL: 168h
