name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install server dependencies
      run: |
        cd server
        yarn install

    # Add Serverless Framework deployment step
    - name: Deploy to AWS Lambda using Serverless Framework
      run: |
        cd server
        yarn global add serverless
        serverless deploy --stage dev
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}