# Name of the workflow
name: Continuous Deployment

# This workflow gets triggered on push events to the main branch
on:
  push:
    branches:
      - main

# Jobs that the workflow will run
jobs:
  # The deploy job
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # A step to install server dependencies
    - name: Install server dependencies
      run: |
        # Change to the server directory
        cd server
        # Install dependencies using yarn
        yarn install

    # A step to deploy to AWS Lambda using Serverless Framework
    - name: Deploy to AWS Lambda using Serverless Framework
      run: |
        # Change to the server directory
        cd server
        # Install Serverless Framework globally
        yarn global add serverless
        # Deploy to the dev stage using Serverless Framework
        serverless deploy --stage dev
      # Environment variables for the step
      env:
        # AWS access key ID from GitHub secrets
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # AWS secret access key from GitHub secrets
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
