name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Add Serverless Framework deployment step
    - name: Deploy to AWS Lambda using Serverless Framework
      run: |
        cd server # Navigate to the server directory if your serverless.yml is there
        npm install -g serverless # Install Serverless Framework globally
        serverless deploy --stage dev # Deploy to AWS Lambda
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


