name: Node.js CI

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20.10.0'] # LTS version of Node.js

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    
    # Install and build for the client
    - name: Install client dependencies
      run: yarn install --frozen-lockfile
      working-directory: client # This should be the relative path from the root of your repo to the client directory
      
    - name: Build client project
      run: yarn build
      working-directory: client # This should be the relative path from the root of your repo to the client directory
      
    # Install and build for the server
    - name: Install server dependencies
      run: yarn install --frozen-lockfile
      working-directory: server # This should be the relative path from the root of your repo to the server directory

    - name: Build server project (if applicable)
      run: yarn build
      working-directory: server # This should be the relative path from the root of your repo to the server directory
      
    # Add any additional steps for testing or other actions below
