name: Node.js CI

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js 20.10.0
      uses: actions/setup-node@v2
      with:
        node-version: '20.10.0'
        cache: 'yarn'
    - name: Install front-end dependencies
      run: |
        cd client
        yarn install
    - name: Build front-end
      run: |
        cd client
        yarn build

  build-backend:
    runs-on: ubuntu-latest
    needs: build-frontend

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js 20.10.0
      uses: actions/setup-node@v2
      with:
        node-version: '20.10.0'
        cache: 'yarn'
    - name: Install back-end dependencies
      run: |
        cd server
        yarn install
    - name: Build back-end
      run: |
        cd server
        yarn build

