name: Node.js CI

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20.10.0'] # LTS version of Node.js

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    
    # Cache for client
    - name: Get yarn cache directory path for client
      run: echo "YARN_CACHE_DIR_CLIENT=$(yarn cache dir)" >> $GITHUB_ENV
      working-directory: client

    - uses: actions/cache@v2
      id: yarn-cache-client
      with:
        path: ${{ env.YARN_CACHE_DIR_CLIENT }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    
    # Install and build for the client
    - name: Install client dependencies
      run: yarn install --frozen-lockfile
      working-directory: client
      
    - name: Build client project
      run: yarn build
      working-directory: client
      
    # Cache for server
    - name: Get yarn cache directory path for server
      run: echo "YARN_CACHE_DIR_SERVER=$(yarn cache dir)" >> $GITHUB_ENV
      working-directory: server

    - uses: actions/cache@v2
      id: yarn-cache-server
      with:
        path: ${{ env.YARN_CACHE_DIR_SERVER }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    
    # Install and build for the server
    - name: Install server dependencies
      run: yarn install --frozen-lockfile
      working-directory: server
