name: Continuous Integration

on: [push, pull_request]

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.10.0'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
       # env:
       #  API_KEY: ${{ secrets.boarding_pass }} 
      - name: Run Linter
        run: npm run lint
      - name: Run Linter
        run: npm run lint

    # Add additional steps for linting, type checks, etc.
